/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compr;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        long[] timeElapsed = new long[19];

        for (int i=0; i<timeElapsed.length; i++) {
            int n = (int) Math.pow(2, i);
            List<Integer> list = IntStream.range(0, n).boxed().collect(Collectors.toList());
            Collections.shuffle(list);
            int[] unorderedArray = list.stream().mapToInt(j -> j).toArray();

            long start = System.currentTimeMillis();
            Sort.insertion(unorderedArray);
            long end = System.currentTimeMillis();
            timeElapsed[i] = end - start;
        }

        System.out.println(Arrays.stream(timeElapsed).boxed().collect(Collectors.toList()));
        
        // Create a dataset for the plot
        XYSeries series = new XYSeries("Time Elapsed");
        for (int i=0; i <timeElapsed.length; i++) series.add(Math.pow(2, i), timeElapsed[i]);

        XYSeriesCollection dataset = new XYSeriesCollection(series);

        // Create the chart
        JFreeChart chart = ChartFactory.createXYLineChart(
            "Time Elapsed vs n", // Chart title
            "n", // X-axis label
            "Time Elapsed", // Y-axis label
            dataset // Dataset
        );

        // Display the chart in a frame
        ChartFrame frame = new ChartFrame("Plot", chart);
        frame.pack();
        frame.setVisible(true);        
    }
}
